url: http://www.hydro-dynamic.at
baseurl: 

# Site settings
title: Smetana cup 2024
email: competition@aida-austria.at
description: "Freediving championships in Austria: 21st-22nd of October 2023 at the BSFZ Südstadt"


# Team names, titles and social links
people:
- name: Já
  pic: 1
  position: Organizer
- name: Zdeňka Hildová
  pic: 5
  position: Rozhodčí
- name: Vendula Strachotová
  pic: 4
  position: Rozhodčí
- name: Michal Bavor
  pic: 3
  position: Rozhodčí
- name: Daniel Doktor
  pic: 2
  position: Asistent
- name: Ralph Staudigl
  pic: 6
  position: Rozhodčí

# - name: Arno Mayrhofer
#   pic: 2
#   position: "Organizer | <a href=\"mailto:competition@aida-austria.at\">Contact</a>"

# - name: Christian "Rossi" Fötinger
#   pic: 3
#   position: Head judge

# - name: Eva Fröstl
#   pic: 8
#   position: Judge

# - name: Maja Bozicek
#   pic: 5
#   position: Judge

# - name: Henriette Kissling
#   pic: 6
#   position: Judge

# - name: Alice Ruf
#   pic: alice_ruf
#   position: Medic

#- name: Roswitha Prohaska
#  pic: 7
#  position: Medic
#
#- name: Wilhelm Welslau
#  pic: 9
#  position: Medic

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/events/728533829204085

# Postal address (add as many lines as necessary)
address:
  - line: A.I.D.A. Austria
  - line: Schlossergasse 3
  - line: 6020 Innsbruck

# Build settings
markdown: kramdown
permalink: pretty
